version: '3.8'
services: 
    web:
        build: .
        ports: 
            - "5000:5000"
        depends_on: 
            - redis
    redis:
        container_name: redis
        hostname: redis
        image: redis:alpine
        command: redis-server --appendonly yes
        ports: 
            - "6379:6379"
